spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?currentSchema=my_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
  main:
    banner-mode: false

server:
  port: 8081
  servlet:
    context-path: /WebAppDB

logging:
  level:
    root: INFO
    ru.bmstu.Lab7: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"